export const teamMembers = [
  {
    id: "member-1",
    name: "Stephanie Li",
    role: "Marketing",
    src: "/images/team/stephanieli.png",
    linkedin: "https://www.linkedin.com/",
  },
  {
    id: "member-2",
    name: "Stephanie Li",
    role: "Marketing",
    src: "/images/team/stephanieli.png",
    linkedin: "https://www.linkedin.com/",
  },
  {
    id: "member-3",
    name: "Stephanie Li",
    role: "Marketing",
    src: "/images/team/stephanieli.png",
    linkedin: "https://www.linkedin.com/",
  },
  {
    id: "member-4",
    name: "Stephanie Li",
    role: "Marketing",
    src: "/images/team/stephanieli.png",
    linkedin: "https://www.linkedin.com/",
  },
  {
    id: "member-5",
    name: "Stephanie Li",
    role: "Marketing",
    src: "/images/team/stephanieli.png",
    linkedin: "https://www.linkedin.com/",
  },
  {
    id: "member-6",
    name: "Stephanie Li",
    role: "Marketing",
    src: "/images/team/stephanieli.png",
    linkedin: "https://www.linkedin.com/",
  },
  {
    id: "member-7",
    name: "Stephanie Li",
    role: "Marketing",
    src: "/images/team/stephanieli.png",
    linkedin: "https://www.linkedin.com/",
  },
  {
    id: "member-8",
    name: "Stephanie Li",
    role: "VP of Marketing",
    src: "/images/team/stephanieli.png",
    linkedin: "https://www.linkedin.com/",
  },
  {
    id: "member-9",
    name: "Stephanie Li",
    role: "Marketing",
    src: "/images/team/stephanieli.png",
    linkedin: "https://www.linkedin.com/",
  },
];
