export const teamMembers = [
  {
    id: "member-1",
    name: "Tina Tang",
    role: "Co-President",
    src: "/images/team/tinatang.webp",
    linkedin: "https://www.linkedin.com/in/tina-ttang/",
  },
  {
    id: "member-2",
    name: "Vishall Balaji B",
    role: "Co-President",
    src: "/images/team/vishallbalaji.webp",
    linkedin: "https://www.linkedin.com/in/vishallbalaji/",
  },
  {
    id: "member-3",
    name: "Adalia Ma",
    role: "VP Marketing",
    src: "/images/team/adaliama.webp",
    linkedin: "https://www.linkedin.com/in/adaliama/",
  },
  {
    id: "member-4",
    name: "Caleb Chen",
    role: "VP Marketing",
    src: "/images/team/calebchen.webp",
    linkedin: "https://www.linkedin.com/in/caleb-chen-823188284/",
  },
  {
    id: "member-5",
    name: "Eric Su",
    role: "VP Finance",
    src: "/images/team/ericsu.webp",
    linkedin: "https://www.linkedin.com/in/eric-su-a523a0344/",
  },
  {
    id: "member-6",
    name: "Abhay Shah",
    role: "VP Finance",
    src: "/images/team/abhayshah.webp",
    linkedin: "https://www.linkedin.com/in/abhay-shah1/",
  },
  {
    id: "member-7",
    name: "Hannah Wu",
    role: "VP Careers",
    src: "/images/team/hannahwu.webp",
    linkedin: "https://www.linkedin.com/in/hannahwuu/",
  },
  {
    id: "member-8",
    name: "Wanyi Chen",
    role: "VP Careers",
    src: "/images/team/wanyichen.webp",
    linkedin: "https://www.linkedin.com/in/wanyichen946/",
  },
  {
    id: "member-9",
    name: "Sarah Gao",
    role: "VP Internal",
    src: "/images/team/sarahgao.webp",
    linkedin: "https://www.linkedin.com/in/sarah-gao-175a79297/",
  },
  {
    id: "member-10",
    name: "Noah Teitlebaum",
    role: "VP Internal",
    src: "/images/team/noahteitlebaum.webp",
    linkedin: "https://www.linkedin.com/in/noahteitlebaum/",
  },
  {
    id: "member-11",
    name: "Audric Liang",
    role: "VP Flagship",
    src: "/images/team/audricliang.webp",
    linkedin: "https://www.linkedin.com/in/audric-liang-5059152a8/",
  },
  {
    id: "member-12",
    name: "Grace Wu",
    role: "VP Flagship",
    src: "/images/team/gracewu.webp",
    linkedin: "https://www.linkedin.com/in/graceywu/",
  },
  {
    id: "member-13",
    name: "Jocelyn Wong",
    role: "VP Flagship",
    src: "/images/team/jocelynwong.webp",
    linkedin: "https://www.linkedin.com/in/jocelyn-wong-03baa42a8/",
  },
  {
    id: "member-14",
    name: "Chang Li",
    role: "VP Development",
    src: "/images/team/changli.webp",
    linkedin: "https://www.linkedin.com/in/shengchangli/",
  },
  {
    id: "member-15",
    name: "Ronit Longia",
    role: "VP Development",
    src: "/images/team/ronitlongia.webp",
    linkedin: "https://www.linkedin.com/in/ronit-longia/",
  },
  {
    id: "member-16",
    name: "Devan Sodhi",
    role: "VP Technology",
    src: "/images/team/devansodhi.webp",
    linkedin: "https://www.linkedin.com/in/devansodhi/",
  },
  {
    id: "member-17",
    name: "Jonathan Zhou",
    role: "VP Technology",
    src: "/images/team/jonathanzhou.webp",
    linkedin: "https://www.linkedin.com/in/jonathanzhou07/",
  },
];
